[automount]
# automount fixed drives with DrvFs
enabled=true
# mount "C:" to "/c"
root = /

[boot]
# enable systemd
systemd=true
#command=service docker start

[network]
#hostname=
#generateHosts=false
#generateResolvConf=false

[Interop]
enabled=false
appendWindowsPath=false

[user]
# login with 'mike'
default=mike
